/**
 * Autocomplete suggestions for various fields
 */

const SUGGESTIONS = {
    locations: [
        'Remote, US',
        'Remote, Worldwide',
        'New York, NY',
        'San Francisco, CA',
        'Los Angeles, CA',
        'Austin, TX',
        'Seattle, WA',
        'Boston, MA',
        'Chicago, IL',
        'Denver, CO',
        'Portland, OR',
        'Washington, DC',
        'Atlanta, GA',
        'Miami, FL',
        'Dallas, TX',
    ],

    jobTitles: [
        'Product Manager',
        'Senior Product Manager',
        'Principal Product Manager',
        'Director of Product',
        'VP of Product',
        'Software Engineer',
        'Senior Software Engineer',
        'Staff Engineer',
        'Principal Engineer',
        'Engineering Manager',
        'Data Scientist',
        'Machine Learning Engineer',
        'DevOps Engineer',
        'Frontend Engineer',
        'Backend Engineer',
        'Full Stack Engineer',
        'Solutions Architect',
        'Technical Program Manager',
    ],

    companies: [
        'Google',
        'Meta',
        'Amazon',
        'Apple',
        'Microsoft',
        'Netflix',
        'Salesforce',
        'Adobe',
        'Uber',
        'Airbnb',
        'Stripe',
        'Square',
        'Coinbase',
        'Datadog',
        'Snowflake',
        'ServiceNow',
        'Atlassian',
        'Splunk',
        'Workday',
        'DocuSign',
    ],

    skills: [
        'Product Strategy',
        'Roadmapping',
        'User Research',
        'Data Analysis',
        'SQL',
        'Python',
        'JavaScript',
        'React',
        'Node.js',
        'AWS',
        'Docker',
        'Kubernetes',
        'Machine Learning',
        'A/B Testing',
        'Agile/Scrum',
        'Stakeholder Management',
        'Technical Writing',
        'API Design',
    ],

    keywords: [
        'remote',
        'flexible hours',
        'stock options',
        'equity',
        '401k',
        'healthcare',
        'unlimited PTO',
        'startup',
        'enterprise',
        'B2B',
        'B2C',
        'SaaS',
        'AI/ML',
        'blockchain',
        'cloud',
        'mobile',
        'web',
    ],
};

// Make SUGGESTIONS available globally
window.SUGGESTIONS = SUGGESTIONS;
